/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.AlphaComposite;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import modelos.LabelError;
import static util.Utils.*;

/**
 *
 * @author danyc
 */
public class ModalLexico extends javax.swing.JFrame {

    private boolean show;

    public ModalLexico(LabelError automata) {
        initComponents();
        setLocationRelativeTo(this);
        show = true;
        icon_close_btn.setIcon(resizeIcon(new ImageIcon(getClass().getResource("/img/close_icon.png")), icon_close_btn.getWidth(), icon_close_btn.getHeight()));
        lb_info_error.setText(automata.getLabel().getText());
        
    }

    public void close() {
        show = false;
        dispose();
    }

    public boolean isOpen() {
        return show;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        icon_close_btn = new javax.swing.JLabel();
        jlbAutomata = new javax.swing.JLabel();
        lb_info_error = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbEstados = new javax.swing.JLabel();
        jlbInicial = new javax.swing.JLabel();
        jlbFinal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlfabeto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoError = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Ayuda sobre error léxico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 60));

        icon_close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        icon_close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                icon_close_btnMouseReleased(evt);
            }
        });
        jPanel1.add(icon_close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 20, 20));

        jlbAutomata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAutomata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jlbAutomata, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 420, 370));

        lb_info_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_info_error.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lb_info_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 610, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 240, 30));

        jlbEstados.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlbEstados.setForeground(new java.awt.Color(0, 0, 0));
        jlbEstados.setText("Q={q1,q2,q3,q4,q5,q6,q7,q8,q9}");
        jPanel1.add(jlbEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 210, 30));

        jlbInicial.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlbInicial.setForeground(new java.awt.Color(0, 0, 0));
        jlbInicial.setText("S=q1");
        jPanel1.add(jlbInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 210, 30));

        jlbFinal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlbFinal.setForeground(new java.awt.Color(0, 0, 0));
        jlbFinal.setText("F={q2,q4,q7,q9}");
        jPanel1.add(jlbFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 210, 30));

        txtAlfabeto.setColumns(20);
        txtAlfabeto.setRows(5);
        txtAlfabeto.setText("Σ={0, 1, 2, 3, 4, 5, 6, 7,8, 9, +, -, *, /, ^, e, .}");
        jScrollPane1.setViewportView(txtAlfabeto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 290, 60));

        InfoError.setColumns(20);
        InfoError.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        InfoError.setForeground(new java.awt.Color(204, 0, 0));
        InfoError.setRows(5);
        jScrollPane2.setViewportView(InfoError);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 290, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon_close_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_close_btnMouseReleased
        this.dispose();
    }//GEN-LAST:event_icon_close_btnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalLexico(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea InfoError;
    private javax.swing.JLabel icon_close_btn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel jlbAutomata;
    public static javax.swing.JLabel jlbEstados;
    public static javax.swing.JLabel jlbFinal;
    public static javax.swing.JLabel jlbInicial;
    private javax.swing.JLabel lb_info_error;
    public static javax.swing.JTextArea txtAlfabeto;
    // End of variables declaration//GEN-END:variables

   
}
