/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.UIDefaults;
import javax.swing.plaf.ColorUIResource;


import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import static util.Utils.resizeIcon;
import codigo.VentanaPrincipal;
import static codigo.VentanaPrincipal.intercode;
import static codigo.VentanaPrincipal.txtAreaEdit;
import java.util.StringTokenizer;
import static javax.swing.JOptionPane.showMessageDialog;



//DE COLORES
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
public class CodigoGenerado extends javax.swing.JDialog {

    /**
     * Creates new form CodigoGenerado1
     */
    public CodigoGenerado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Código Intermedio Generado");
        //CAMBIAR COLOR DEL JTEXTPANE-----------------------------------------------------------------
        Color bgColor = new Color(42, 43, 46);
        UIDefaults defaults = new UIDefaults();
        defaults.put("TextPane.background", new ColorUIResource(bgColor));
        defaults.put("TextPane[Enabled].backgroundPainter", bgColor);
        txtcod.putClientProperty("Nimbus.Overrides", defaults);
        txtcod.putClientProperty("Nimbus.Overrides.InheritDefaults", true);
        txtcod.setBackground(bgColor);
        //----------------------------------------------------------------------------------------------------
        
        this.setLocationRelativeTo(this);
        seticon();
    }
        public CodigoGenerado(java.awt.Frame parent, boolean modal, String codigoArduino) {
        super(parent, modal);
        initComponents();
        this.setTitle("Código Intermedio Generado");
        //CAMBIAR COLOR DEL JTEXTPANE-----------------------------------------------------------------
        Color bgColor = new Color(42, 43, 46);
        UIDefaults defaults = new UIDefaults();
        defaults.put("TextPane.background", new ColorUIResource(bgColor));
        defaults.put("TextPane[Enabled].backgroundPainter", bgColor);
        txtcod.putClientProperty("Nimbus.Overrides", defaults);
        txtcod.putClientProperty("Nimbus.Overrides.InheritDefaults", true);
        txtcod.setBackground(bgColor);
        //----------------------------------------------------------------------------------------------------
        
        this.setLocationRelativeTo(this);
        seticon();
        llenarcodigo2(codigoArduino);
    }
    public void llenarcodigo2(String arduino){
        txtcod.setText(arduino);
    }
            
            public void llenarcodigo(){
            String a[] = VentanaPrincipal.txtAreaEdit.getText().split("\n");
            
            String cadena="";
            
            
            for(int i=0; i<a.length; i++){
                VentanaPrincipal.intercode2.add(a[i]);
            }
            
            for(int i=0; i<VentanaPrincipal.intercode2.size(); i++){
                
                txtcod.setText(VentanaPrincipal.intercode2.get(i));
               
                if(i==0){VentanaPrincipal.intercode2.set(i, "void setup() {");}
                
                if(VentanaPrincipal.intercode2.get(i).contains("begin")){VentanaPrincipal.intercode2.remove(i);}
                
                if(VentanaPrincipal.intercode2.get(i).contains("just")){VentanaPrincipal.intercode2.set(i, 
                        VentanaPrincipal.intercode2.get(i).replace("just", "int"));}
                
                if(i==VentanaPrincipal.intercode2.size()-1){VentanaPrincipal.intercode2.set(i, "}");}
                
                
                cadena = cadena +"\n"+ VentanaPrincipal.intercode2.get(i);
                
            }
            txtcod.setText(cadena);
            
    }        
    
            
    public void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logopro2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcod = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFocusable(false);

        txtcod.setEditable(false);
        txtcod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcod.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(txtcod);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodigoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodigoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodigoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodigoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CodigoGenerado dialog = new CodigoGenerado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtcod;
    // End of variables declaration//GEN-END:variables
}
