/* The following code was generated by JFlex 1.4.3 on 11/09/21 20:02 */

package codigo;
import java.io.*;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/09/21 20:02 from the specification file
 * <tt>C:/ANADAN/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\42\2\0\1\4\22\0\1\4\1\50\1\6\1\0"+
    "\1\64\1\47\1\51\1\0\1\55\1\56\1\46\1\44\1\40\1\45"+
    "\1\41\1\5\12\2\1\0\1\63\1\53\1\43\1\54\1\65\1\0"+
    "\32\3\1\61\1\0\1\62\1\0\1\1\1\0\1\21\1\36\1\26"+
    "\1\12\1\14\1\16\1\27\1\34\1\17\1\35\1\37\1\20\1\22"+
    "\1\23\1\10\1\25\1\1\1\11\1\13\1\15\1\31\1\33\1\7"+
    "\1\30\1\24\1\32\1\57\1\52\1\60\101\0\1\66\uff40\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\17\2\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\2\1\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\2\1\31\2\32\3\0"+
    "\1\4\1\0\1\33\1\0\2\2\1\34\16\2\1\35"+
    "\20\2\1\36\1\0\1\37\1\0\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\31\1\3\1\0\13\2\1\46"+
    "\2\2\1\47\6\2\1\50\3\2\1\51\2\2\1\52"+
    "\5\2\1\53\1\0\1\54\6\2\1\55\1\2\1\56"+
    "\1\57\1\2\1\60\1\61\1\2\1\62\3\2\1\63"+
    "\2\2\1\64\5\2\1\65\1\66\1\67\2\2\2\0"+
    "\1\70\7\2\1\71\1\72\3\2\1\73\1\74\2\2"+
    "\1\75\1\76\5\2\1\77\1\53\1\0\3\2\1\100"+
    "\2\2\1\101\3\2\1\102\1\2\1\103\3\2\1\104"+
    "\1\32\46\2\1\105\4\2\1\106\12\2\1\107\2\2"+
    "\1\110\1\2\1\111\3\2\1\112\1\113\1\114\1\115"+
    "\2\2\1\116\2\2\1\117\3\2\1\120\1\121\1\2"+
    "\1\122\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[298];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181"+
    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u0339"+
    "\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u0113"+
    "\0\67\0\67\0\u04f1\0\u0528\0\u055f\0\u014a\0\67\0\u0596"+
    "\0\u05cd\0\u0604\0\u063b\0\u0672\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785"+
    "\0\334\0\u014a\0\u014a\0\u07bc\0\67\0\u07f3\0\u082a\0\u0861"+
    "\0\156\0\u0898\0\u08cf\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2"+
    "\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\156"+
    "\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b"+
    "\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3"+
    "\0\67\0\u0717\0\67\0\u0f0a\0\67\0\67\0\67\0\67"+
    "\0\67\0\67\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054"+
    "\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c"+
    "\0\156\0\u1243\0\u127a\0\156\0\u12b1\0\u12e8\0\u131f\0\u1356"+
    "\0\u138d\0\u13c4\0\156\0\u13fb\0\u1432\0\u1469\0\156\0\u14a0"+
    "\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621\0\u1658"+
    "\0\u168f\0\156\0\u16c6\0\u16fd\0\u1734\0\u176b\0\u17a2\0\u17d9"+
    "\0\156\0\u1810\0\156\0\156\0\u1847\0\156\0\156\0\u187e"+
    "\0\156\0\u18b5\0\u18ec\0\u1923\0\156\0\u195a\0\u1991\0\156"+
    "\0\u19c8\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4\0\156\0\156\0\156"+
    "\0\u1adb\0\u1b12\0\u1b49\0\u1b80\0\156\0\u1bb7\0\u1bee\0\u1c25"+
    "\0\u1c5c\0\u1c93\0\u1cca\0\u1d01\0\156\0\156\0\u1d38\0\u1d6f"+
    "\0\u1da6\0\156\0\156\0\u1ddd\0\u1e14\0\156\0\156\0\u1e4b"+
    "\0\u1e82\0\u1eb9\0\u1ef0\0\u1f27\0\156\0\u1b49\0\u1f5e\0\u1f95"+
    "\0\u1fcc\0\u2003\0\156\0\u203a\0\u2071\0\156\0\u20a8\0\u20df"+
    "\0\u2116\0\156\0\u214d\0\156\0\u2184\0\u21bb\0\u21f2\0\156"+
    "\0\u2229\0\u2260\0\u2297\0\u22ce\0\u2305\0\u233c\0\u2373\0\u23aa"+
    "\0\u23e1\0\u2418\0\u244f\0\u2486\0\u24bd\0\u24f4\0\u252b\0\u2562"+
    "\0\u2599\0\u25d0\0\u2607\0\u263e\0\u2675\0\u26ac\0\u26e3\0\u271a"+
    "\0\u2751\0\u2788\0\u27bf\0\u27f6\0\u282d\0\u2864\0\u289b\0\u28d2"+
    "\0\u2909\0\u2940\0\u2977\0\u29ae\0\u29e5\0\u2a1c\0\u2a53\0\156"+
    "\0\u2a8a\0\u2ac1\0\u2af8\0\u2b2f\0\156\0\u2b66\0\u2b9d\0\u2bd4"+
    "\0\u2c0b\0\u2c42\0\u2c79\0\u2cb0\0\u2ce7\0\u2d1e\0\u2d55\0\156"+
    "\0\u2d8c\0\u2dc3\0\u2dfa\0\u2e31\0\156\0\u2e68\0\u2e9f\0\u2ed6"+
    "\0\156\0\156\0\156\0\156\0\u2f0d\0\u2f44\0\156\0\u2f7b"+
    "\0\u2fb2\0\156\0\u2fe9\0\u3020\0\u3057\0\156\0\156\0\u308e"+
    "\0\156\0\156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[298];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\3\1\12\1\13\1\14\1\15\1\16\1\17\2\3"+
    "\1\20\1\21\1\3\1\22\1\23\1\24\4\3\1\25"+
    "\1\26\1\27\1\3\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\3\2"+
    "\70\0\1\3\1\54\1\55\3\0\31\3\1\0\1\56"+
    "\26\0\1\57\1\4\4\0\31\57\1\0\1\60\26\0"+
    "\1\57\1\0\1\61\3\0\31\57\33\0\1\6\33\0"+
    "\1\6\26\0\5\62\1\63\40\62\1\63\20\62\6\64"+
    "\1\65\55\64\1\66\2\64\1\0\1\3\1\54\1\55"+
    "\3\0\1\3\1\67\23\3\1\70\3\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\1\3\1\71\1\72"+
    "\2\3\1\73\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\5\3\1\74\1\75\2\3\1\76\1\77"+
    "\16\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\11\3\1\100\1\3\1\101\1\102\14\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\2\3\1\103\26\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\1\3"+
    "\1\104\6\3\1\105\1\106\1\107\16\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\7\3\1\110\21\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\1\3"+
    "\1\111\3\3\1\112\4\3\1\113\16\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\5\3\1\114\23\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\2\3"+
    "\1\115\26\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\11\3\1\116\1\117\7\3\1\120\2\3\1\121"+
    "\3\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\1\3\1\122\3\3\1\123\2\3\1\124\20\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\1\3\1\125"+
    "\27\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\22\3\1\126\6\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\2\3\1\127\2\3\1\130\23\3\1\0"+
    "\1\56\70\0\1\131\24\0\1\132\1\4\4\0\31\132"+
    "\4\0\1\133\1\134\22\0\1\132\1\4\4\0\31\132"+
    "\4\0\1\134\1\135\64\0\1\136\74\0\1\137\67\0"+
    "\1\140\57\0\1\141\66\0\1\142\24\0\2\54\4\0"+
    "\31\54\1\0\1\56\26\0\1\143\1\0\1\55\3\0"+
    "\31\143\30\0\2\56\4\0\31\56\1\0\1\56\26\0"+
    "\2\57\4\0\31\57\31\0\1\144\64\0\6\64\1\65"+
    "\66\64\1\65\42\64\1\145\15\64\1\0\1\3\1\54"+
    "\1\55\3\0\2\3\1\146\26\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\10\3\1\147\20\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\12\3\1\150"+
    "\16\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\7\3\1\151\21\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\6\3\1\152\2\3\1\153\17\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\1\3\1\154"+
    "\27\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\5\3\1\155\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\13\3\1\156\15\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\4\3\1\157\24\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\16\3\1\160"+
    "\12\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\3\3\1\161\25\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\12\3\1\162\7\3\1\163\6\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\2\3\1\164"+
    "\26\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\11\3\1\165\17\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\12\3\1\166\16\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\11\3\1\167\17\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\3\3\1\170"+
    "\25\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\6\3\1\171\22\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\10\3\1\172\20\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\1\173\30\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\10\3\1\174\20\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\12\3"+
    "\1\175\16\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\4\3\1\176\24\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\6\3\1\177\22\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\5\3\1\200\23\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\27\3"+
    "\1\201\1\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\6\3\1\202\22\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\24\3\1\203\4\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\13\3\1\204\15\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\4\3"+
    "\1\205\24\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\1\3\1\206\27\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\20\3\1\207\10\3\1\0\1\56"+
    "\27\0\1\210\65\0\1\143\5\0\31\143\30\0\1\56"+
    "\1\144\4\0\31\56\1\0\1\56\25\0\6\64\1\65"+
    "\56\64\1\211\1\64\1\0\1\3\1\54\1\55\3\0"+
    "\3\3\1\212\25\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\11\3\1\213\17\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\1\214\30\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\5\3\1\215\23\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\7\3"+
    "\1\216\4\3\1\217\14\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\5\3\1\220\23\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\16\3\1\221\12\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\5\3"+
    "\1\222\23\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\5\3\1\223\23\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\5\3\1\224\23\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\6\3\1\225\22\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\16\3"+
    "\1\226\12\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\5\3\1\227\23\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\11\3\1\230\17\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\20\3\1\231\10\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\4\3"+
    "\1\232\24\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\5\3\1\233\23\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\25\3\1\234\3\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\14\3\1\235\14\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\14\3"+
    "\1\236\14\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\4\3\1\237\24\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\5\3\1\240\23\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\17\3\1\241\11\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\12\3"+
    "\1\242\16\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\5\3\1\243\1\244\1\245\21\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\5\3\1\246\23\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\5\3"+
    "\1\247\23\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\6\3\1\250\22\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\30\3\1\251\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\10\3\1\252\20\3\1\0"+
    "\1\56\27\0\1\210\36\0\1\253\25\0\6\64\1\65"+
    "\57\64\1\254\1\0\1\3\1\54\1\55\3\0\5\3"+
    "\1\255\23\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\2\3\1\256\3\3\1\257\10\3\1\260\11\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\17\3"+
    "\1\261\11\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\10\3\1\262\20\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\5\3\1\263\23\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\17\3\1\264\11\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\16\3"+
    "\1\265\12\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\15\3\1\266\13\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\2\3\1\267\3\3\1\270\10\3"+
    "\1\271\11\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\5\3\1\272\23\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\11\3\1\273\17\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\1\3\1\274\27\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\6\3"+
    "\1\275\22\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\4\3\1\276\24\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\30\3\1\277\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\17\3\1\300\11\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\21\3\1\301"+
    "\7\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\5\3\1\302\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\10\3\1\303\20\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\304\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\14\3\1\305"+
    "\14\3\1\0\1\56\27\0\1\306\64\0\6\64\1\65"+
    "\40\64\1\307\17\64\1\0\1\3\1\54\1\55\3\0"+
    "\5\3\1\310\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\2\3\1\311\26\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\10\3\1\312\20\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\6\3\1\313"+
    "\22\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\11\3\1\314\17\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\1\315\30\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\6\3\1\316\22\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\5\3\1\317\23\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\2\3"+
    "\1\320\26\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\10\3\1\321\20\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\3\3\1\322\25\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\5\3\1\323\23\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\30\3"+
    "\1\324\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\6\3\1\325\22\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\13\3\1\326\15\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\11\3\1\327\17\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\14\3\1\330"+
    "\14\3\1\0\1\56\25\0\1\64\1\331\4\64\1\65"+
    "\31\331\27\64\1\0\1\3\1\54\1\55\3\0\17\3"+
    "\1\332\11\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\10\3\1\333\20\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\2\3\1\334\26\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\12\3\1\335\16\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\7\3"+
    "\1\336\21\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\17\3\1\337\11\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\10\3\1\340\20\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\2\3\1\341\26\3"+
    "\1\0\1\56\26\0\1\3\1\54\1\55\3\0\2\3"+
    "\1\342\26\3\1\0\1\56\26\0\1\3\1\54\1\55"+
    "\3\0\2\3\1\343\26\3\1\0\1\56\26\0\1\3"+
    "\1\54\1\55\3\0\16\3\1\344\12\3\1\0\1\56"+
    "\26\0\1\3\1\54\1\55\3\0\12\3\1\345\16\3"+
    "\1\0\1\56\25\0\1\64\2\331\3\64\1\65\31\331"+
    "\27\64\1\0\1\3\1\54\1\55\3\0\6\3\1\346"+
    "\22\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\12\3\1\347\16\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\17\3\1\350\11\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\13\3\1\351\15\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\10\3\1\352"+
    "\20\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\6\3\1\353\22\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\12\3\1\354\16\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\17\3\1\355\11\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\16\3\1\356"+
    "\12\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\22\3\1\357\6\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\5\3\1\360\23\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\13\3\1\361\15\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\12\3\1\362"+
    "\16\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\14\3\1\363\14\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\11\3\1\364\17\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\365\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\11\3\1\366"+
    "\17\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\12\3\1\367\16\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\14\3\1\370\14\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\11\3\1\371\17\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\1\3\1\372"+
    "\27\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\4\3\1\373\24\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\2\3\1\374\26\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\375\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\14\3\1\376"+
    "\14\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\20\3\1\377\10\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\5\3\1\u0100\23\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\14\3\1\u0101\14\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\12\3\1\u0102"+
    "\16\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\14\3\1\u0103\14\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\20\3\1\u0104\10\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\u0105\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\2\3\1\u0106"+
    "\26\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\1\3\1\u0107\27\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\12\3\1\u0108\16\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\14\3\1\u0109\14\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\20\3\1\u010a"+
    "\10\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\11\3\1\u010b\17\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\6\3\1\u010c\22\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\13\3\1\u010d\15\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\20\3\1\u010e"+
    "\10\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\11\3\1\u010f\17\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\6\3\1\u0110\22\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\2\3\1\u0111\26\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\6\3\1\u0112"+
    "\22\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\6\3\1\u0113\22\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\11\3\1\u0114\17\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\u0115\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\6\3\1\u0116"+
    "\22\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\5\3\1\u0117\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\11\3\1\u0118\17\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\u0119\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\15\3\1\u011a"+
    "\3\3\1\u011b\1\3\1\u011c\5\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\22\3\1\u011d\6\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\6\3\1\u011e"+
    "\22\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\5\3\1\u011f\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\15\3\1\u0120\13\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\14\3\1\u0121\14\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\5\3\1\u0122"+
    "\23\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\2\3\1\u0123\26\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\15\3\1\u0124\13\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\16\3\1\u0125\12\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\6\3\1\u0126"+
    "\22\3\1\0\1\56\26\0\1\3\1\54\1\55\3\0"+
    "\5\3\1\u0127\23\3\1\0\1\56\26\0\1\3\1\54"+
    "\1\55\3\0\16\3\1\u0128\12\3\1\0\1\56\26\0"+
    "\1\3\1\54\1\55\3\0\5\3\1\u0129\23\3\1\0"+
    "\1\56\26\0\1\3\1\54\1\55\3\0\5\3\1\u012a"+
    "\23\3\1\0\1\56\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12485];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\26\1\2\11\4\1\1\11\5\1\7\11"+
    "\4\1\3\0\1\1\1\0\1\11\1\0\42\1\1\11"+
    "\1\0\1\11\1\0\6\11\2\1\1\0\43\1\1\0"+
    "\41\1\2\0\32\1\1\0\143\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[298];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    InformacionLexema c = new InformacionLexema();


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 39: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return For;
          }
        case 84: break;
        case 42: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Get;
          }
        case 85: break;
        case 5: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Signo_de_División;
          }
        case 86: break;
        case 21: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Llave_Cierra;
          }
        case 87: break;
        case 22: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Corchete_Abre ;
          }
        case 88: break;
        case 61: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Class;
          }
        case 89: break;
        case 73: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Drawtriangle;
          }
        case 90: break;
        case 15: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return NOT;
          }
        case 91: break;
        case 53: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Give;
          }
        case 92: break;
        case 29: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return If;
          }
        case 93: break;
        case 69: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Drawcircle;
          }
        case 94: break;
        case 71: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Printerport;
          }
        case 95: break;
        case 27: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Cadena;
          }
        case 96: break;
        case 70: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Fillcircle;
          }
        case 97: break;
        case 59: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return False;
          }
        case 98: break;
        case 35: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return OR;
          }
        case 99: break;
        case 3: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Numero;
          }
        case 100: break;
        case 4: 
          { /*Ignore*/
          }
        case 101: break;
        case 68: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Broken;
          }
        case 102: break;
        case 33: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Diferente_que;
          }
        case 103: break;
        case 78: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Drawrectangle;
          }
        case 104: break;
        case 17: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Mayor_que;
          }
        case 105: break;
        case 83: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Getfilamenttype;
          }
        case 106: break;
        case 77: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Getextrusorz;
          }
        case 107: break;
        case 74: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Filltriangle;
          }
        case 108: break;
        case 38: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return End;
          }
        case 109: break;
        case 82: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Setfilamenttype;
          }
        case 110: break;
        case 11: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Signo_de_Suma;
          }
        case 111: break;
        case 24: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return PuntoYComa;
          }
        case 112: break;
        case 54: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Home;
          }
        case 113: break;
        case 8: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Punto;
          }
        case 114: break;
        case 6: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return COMILLAS_DOBLES;
          }
        case 115: break;
        case 1: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return ERROR;
          }
        case 116: break;
        case 34: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return AND;
          }
        case 117: break;
        case 41: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Cut;
          }
        case 118: break;
        case 72: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Getfilament;
          }
        case 119: break;
        case 64: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Defect;
          }
        case 120: break;
        case 75: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Getextrusory;
          }
        case 121: break;
        case 31: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Mas_Mas;
          }
        case 122: break;
        case 25: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return MAYUSCULAS_EN_CADENA;
          }
        case 123: break;
        case 80: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Setnewfilament;
          }
        case 124: break;
        case 37: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Mayor_o_igual_que;
          }
        case 125: break;
        case 55: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Just;
          }
        case 126: break;
        case 79: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Fillrectangle;
          }
        case 127: break;
        case 63: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Begin;
          }
        case 128: break;
        case 14: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Signo_de_Residuo;
          }
        case 129: break;
        case 44: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Word;
          }
        case 130: break;
        case 26: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return MAL_NOMBRE_PARA_IDENTIFICADOR;
          }
        case 131: break;
        case 66: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Method;
          }
        case 132: break;
        case 45: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Stop;
          }
        case 133: break;
        case 12: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Signo_de_Resta;
          }
        case 134: break;
        case 58: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Empty;
          }
        case 135: break;
        case 67: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Goback;
          }
        case 136: break;
        case 76: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Getextrusorx;
          }
        case 137: break;
        case 18: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Parentesis_Abre;
          }
        case 138: break;
        case 57: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Sleep;
          }
        case 139: break;
        case 81: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Gettemperature;
          }
        case 140: break;
        case 32: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Menos_Menos;
          }
        case 141: break;
        case 65: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Select;
          }
        case 142: break;
        case 47: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Else;
          }
        case 143: break;
        case 56: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return While;
          }
        case 144: break;
        case 10: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Signo_de_igual;
          }
        case 145: break;
        case 30: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Igual_que;
          }
        case 146: break;
        case 43: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return NUMERO_ERRONEO;
          }
        case 147: break;
        case 50: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Flag;
          }
        case 148: break;
        case 51: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Main;
          }
        case 149: break;
        case 20: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Llave_Abre;
          }
        case 150: break;
        case 36: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Menor_o_igual_que;
          }
        case 151: break;
        case 40: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return New;
          }
        case 152: break;
        case 9: 
          { return Linea;
          }
        case 153: break;
        case 62: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Check;
          }
        case 154: break;
        case 60: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Model;
          }
        case 155: break;
        case 52: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Case;
          }
        case 156: break;
        case 19: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Parentesis_Cierra;
          }
        case 157: break;
        case 48: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Trap;
          }
        case 158: break;
        case 28: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Do;
          }
        case 159: break;
        case 2: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Identificador;
          }
        case 160: break;
        case 23: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Corchete_Cierra;
          }
        case 161: break;
        case 13: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Signo_de_Multiplicación;
          }
        case 162: break;
        case 46: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Same;
          }
        case 163: break;
        case 49: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return True;
          }
        case 164: break;
        case 7: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Coma;
          }
        case 165: break;
        case 16: 
          { c.linea=yyline;c.columna=yycolumn;lexeme=yytext(); return Menor_que;
          }
        case 166: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
