
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 09 19:14:33 MDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Mayor_que = 58;
  public static final int Sleep = 5;
  public static final int Fillrectangle = 3;
  public static final int Signo_de_División = 50;
  public static final int Coma = 75;
  public static final int True = 73;
  public static final int Punto = 77;
  public static final int Goback = 37;
  public static final int Setnewfilament = 15;
  public static final int Signo_de_Residuo = 51;
  public static final int Flag = 29;
  public static final int Corchete_Cierra = 68;
  public static final int Method = 41;
  public static final int Home = 39;
  public static final int Menor_o_igual_que = 59;
  public static final int For = 22;
  public static final int Else = 24;
  public static final int Corchete_Abre = 67;
  public static final int Trap = 43;
  public static final int NOT = 52;
  public static final int Model = 33;
  public static final int Check = 42;
  public static final int Cut = 30;
  public static final int Llave_Cierra = 66;
  public static final int ERROR = 79;
  public static final int Parentesis_Cierra = 64;
  public static final int Cadena = 76;
  public static final int Diferente_que = 61;
  public static final int Gettemperature = 17;
  public static final int Main = 45;
  public static final int Begin = 32;
  public static final int Printerport = 40;
  public static final int Filltriangle = 8;
  public static final int Do = 36;
  public static final int Signo_de_igual = 46;
  public static final int Mas_Mas = 55;
  public static final int Llave_Abre = 65;
  public static final int MAL_NOMBRE_PARA_IDENTIFICADOR = 81;
  public static final int PuntoYComa = 69;
  public static final int Getfilament = 16;
  public static final int Broken = 38;
  public static final int End = 18;
  public static final int Defect = 34;
  public static final int Getfilamenttype = 14;
  public static final int Case = 28;
  public static final int New = 35;
  public static final int Mayor_o_igual_que = 60;
  public static final int Setfilamenttype = 2;
  public static final int Menos_Menos = 56;
  public static final int If = 23;
  public static final int Igual_que = 62;
  public static final int EOF = 0;
  public static final int Parentesis_Abre = 63;
  public static final int Numero = 71;
  public static final int Signo_de_Resta = 48;
  public static final int MAYUSCULAS_EN_CADENA = 80;
  public static final int OR = 54;
  public static final int error = 1;
  public static final int False = 74;
  public static final int Word = 72;
  public static final int Get = 20;
  public static final int NUMERO_ERRONEO = 78;
  public static final int Menor_que = 57;
  public static final int Drawtriangle = 9;
  public static final int Drawcircle = 7;
  public static final int Identificador = 70;
  public static final int Select = 25;
  public static final int Drawrectangle = 4;
  public static final int Empty = 26;
  public static final int Give = 21;
  public static final int Fillcircle = 6;
  public static final int Class = 44;
  public static final int Getextrusorz = 13;
  public static final int Getextrusory = 12;
  public static final int Signo_de_Suma = 47;
  public static final int Same = 19;
  public static final int Getextrusorx = 11;
  public static final int Stop = 10;
  public static final int AND = 53;
  public static final int Signo_de_Multiplicación = 49;
  public static final int While = 27;
  public static final int Just = 31;
}

