
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 25 22:59:28 MST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 2;
  public static final int BROKEN = 8;
  public static final int DRAWRECTANGLE = 14;
  public static final int DEFECT = 42;
  public static final int MENOR_QUE = 64;
  public static final int PARENTESIS_ABRE = 70;
  public static final int GETFILAMENTTYPE = 24;
  public static final int PARENTESIS_CIERRA = 71;
  public static final int SETFILAMENTTYPE = 12;
  public static final int GET = 30;
  public static final int WORD = 10;
  public static final int LEFTTEMPLE = 83;
  public static final int RIGHTRIM = 81;
  public static final int FILLCIRCLE = 16;
  public static final int MENOR_O_IGUAL_QUE = 66;
  public static final int FILLTRIANGLE = 18;
  public static final int GETTEMPERATURE = 27;
  public static final int SIGNO_DE_DIVISIÓN = 57;
  public static final int FILLRECTANGLE = 13;
  public static final int SIGNO_DE_RESIDUO = 58;
  public static final int NUMERO = 3;
  public static final int GIVE = 31;
  public static final int MAYOR_QUE = 65;
  public static final int DRAWCIRCLE = 17;
  public static final int CORCHETE_ABRE = 74;
  public static final int SAME = 29;
  public static final int FALSE = 7;
  public static final int SIGNO_DE_IGUAL = 53;
  public static final int NOT = 59;
  public static final int STOP = 20;
  public static final int ERROR = 87;
  public static final int DIFERENTE_QUE = 68;
  public static final int JUST = 9;
  public static final int LEFTRIM = 82;
  public static final int TEMPLATES = 86;
  public static final int EMPTY = 36;
  public static final int CLASS = 51;
  public static final int SELECT = 35;
  public static final int COMA = 78;
  public static final int LLAVE_CIERRA = 73;
  public static final int TRUE = 6;
  public static final int WHILE = 37;
  public static final int DECIMAL = 4;
  public static final int FLAG = 11;
  public static final int PUNTOYCOMA = 77;
  public static final int MAYOR_O_IGUAL_QUE = 67;
  public static final int SIGNO_DE_EXPONENTE = 75;
  public static final int HOME = 46;
  public static final int DO = 44;
  public static final int FOR = 32;
  public static final int SLEEP = 15;
  public static final int SIGNO_DE_RESTA = 55;
  public static final int ELSE = 34;
  public static final int DRAWTRIANGLE = 19;
  public static final int LLAVE_ABRE = 72;
  public static final int EOF = 0;
  public static final int PUNTO = 79;
  public static final int TRAP = 50;
  public static final int CUT = 39;
  public static final int GOBACK = 45;
  public static final int GETEXTRUSORZ = 23;
  public static final int GETEXTRUSORY = 22;
  public static final int GETEXTRUSORX = 21;
  public static final int MAIN = 52;
  public static final int PRINTERPORT = 47;
  public static final int METHOD = 48;
  public static final int OR = 61;
  public static final int error = 1;
  public static final int RIGHTTEMPLE = 80;
  public static final int IGUAL_QUE = 69;
  public static final int IF = 33;
  public static final int BRIDGE = 84;
  public static final int SIGNO_DE_SUMA = 54;
  public static final int END = 28;
  public static final int CADENA_TEXTO = 5;
  public static final int CHECK = 49;
  public static final int MODEL = 41;
  public static final int SIGNO_DE_MULTIPLICACIÓN = 56;
  public static final int BEGIN = 40;
  public static final int CASE = 38;
  public static final int MAS_MAS = 62;
  public static final int NEW = 43;
  public static final int MENOS_MENOS = 63;
  public static final int GETFILAMENT = 26;
  public static final int RIMS = 85;
  public static final int AND = 60;
  public static final int CORCHETE_CIERRA = 76;
  public static final int SETNEWFILAMENT = 25;
}

