
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 03 19:39:45 MDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 2;
  public static final int BROKEN = 7;
  public static final int DRAWRECTANGLE = 13;
  public static final int DEFECT = 41;
  public static final int MENOR_QUE = 63;
  public static final int PARENTESIS_ABRE = 69;
  public static final int GETFILAMENTTYPE = 23;
  public static final int PARENTESIS_CIERRA = 70;
  public static final int SETFILAMENTTYPE = 11;
  public static final int GET = 29;
  public static final int WORD = 9;
  public static final int FILLCIRCLE = 15;
  public static final int MENOR_O_IGUAL_QUE = 65;
  public static final int FILLTRIANGLE = 17;
  public static final int GETTEMPERATURE = 26;
  public static final int SIGNO_DE_DIVISIÓN = 56;
  public static final int FILLRECTANGLE = 12;
  public static final int SIGNO_DE_RESIDUO = 57;
  public static final int NUMERO = 3;
  public static final int GIVE = 30;
  public static final int MAYOR_QUE = 64;
  public static final int DRAWCIRCLE = 16;
  public static final int CORCHETE_ABRE = 73;
  public static final int SAME = 28;
  public static final int FALSE = 6;
  public static final int SIGNO_DE_IGUAL = 52;
  public static final int NOT = 58;
  public static final int STOP = 19;
  public static final int ERROR = 78;
  public static final int DIFERENTE_QUE = 67;
  public static final int JUST = 8;
  public static final int EMPTY = 35;
  public static final int CLASS = 50;
  public static final int SELECT = 34;
  public static final int COMA = 76;
  public static final int LLAVE_CIERRA = 72;
  public static final int TRUE = 5;
  public static final int WHILE = 36;
  public static final int FLAG = 10;
  public static final int PUNTOYCOMA = 75;
  public static final int MAYOR_O_IGUAL_QUE = 66;
  public static final int HOME = 45;
  public static final int DO = 43;
  public static final int FOR = 31;
  public static final int SLEEP = 14;
  public static final int SIGNO_DE_RESTA = 54;
  public static final int ELSE = 33;
  public static final int DRAWTRIANGLE = 18;
  public static final int LLAVE_ABRE = 71;
  public static final int EOF = 0;
  public static final int PUNTO = 77;
  public static final int TRAP = 49;
  public static final int CUT = 38;
  public static final int GOBACK = 44;
  public static final int GETEXTRUSORZ = 22;
  public static final int GETEXTRUSORY = 21;
  public static final int GETEXTRUSORX = 20;
  public static final int MAIN = 51;
  public static final int PRINTERPORT = 46;
  public static final int METHOD = 47;
  public static final int OR = 60;
  public static final int error = 1;
  public static final int IGUAL_QUE = 68;
  public static final int IF = 32;
  public static final int SIGNO_DE_SUMA = 53;
  public static final int END = 27;
  public static final int CADENA_TEXTO = 4;
  public static final int CHECK = 48;
  public static final int MODEL = 40;
  public static final int SIGNO_DE_MULTIPLICACIÓN = 55;
  public static final int BEGIN = 39;
  public static final int CASE = 37;
  public static final int MAS_MAS = 61;
  public static final int NEW = 42;
  public static final int MENOS_MENOS = 62;
  public static final int GETFILAMENT = 25;
  public static final int AND = 59;
  public static final int CORCHETE_CIERRA = 74;
  public static final int SETNEWFILAMENT = 24;
}

